version: "3"
services:
  transactions:
    build: .
    container_name: transactions
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transactionsdb:5432/testdb
    ports:
      - 8083:8080
    restart: always
    depends_on:
      - transactionsdb

  transactionsdb:
    image: postgres
    container_name: transactionsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: